INSERT INTO city (name, country) VALUES ('Liverpool', 'UK');
INSERT INTO city (name, country) VALUES ('London', 'UK');
INSERT INTO city (name, country) VALUES ('Nottingham', 'UK');
INSERT INTO city (name, country) VALUES ('Birmingham', 'UK');
INSERT INTO city (name, country) VALUES ('Leeds', 'UK');
INSERT INTO city (name, country) VALUES ('Manchester', 'UK');
INSERT INTO city (name, country) VALUES ('Leicester', 'UK');
INSERT INTO city (name, country) VALUES ('Newcastle', 'UK');
INSERT INTO city (name, country) VALUES ('Southampton', 'UK');
INSERT INTO city (name, country) VALUES ('Sheffield', 'UK');
INSERT INTO city (name, country) VALUES ('Bournemouth', 'UK');
INSERT INTO city (name, country) VALUES ('Brighton', 'UK');
INSERT INTO city (name, country) VALUES ('Wolverhampton', 'UK');
INSERT INTO city (name, country) VALUES ('West Bromwich', 'UK');
INSERT INTO city (name, country) VALUES ('Luton', 'UK');
INSERT INTO city (name, country) VALUES ('Brentford', 'UK');
INSERT INTO city (name, country) VALUES ('Burnley', 'UK');
INSERT INTO city (name, country) VALUES ('Norwich', 'UK');
INSERT INTO city (name, country) VALUES ('Watford', 'UK');

INSERT INTO stadium (capacity,fk_city_id,name) VALUES (30750, 12, 'Amex Stadium');
INSERT INTO stadium (capacity,fk_city_id,name) VALUES (61074, 1, 'Anfield');
INSERT INTO stadium (capacity,fk_city_id,name) VALUES (33000, 10, 'Bramall Lane');
INSERT INTO stadium (capacity,fk_city_id,name) VALUES (17250, 16, 'Gtech Community Stadium');
INSERT INTO stadium (capacity,fk_city_id,name) VALUES (30602, 3, 'City Ground');
INSERT INTO stadium (capacity,fk_city_id,name) VALUES (25700, 2, 'Craven Cottage');
INSERT INTO stadium (capacity,fk_city_id,name) VALUES (60704, 2, 'Emirates Stadium');
INSERT INTO stadium (capacity,fk_city_id,name) VALUES (55097, 6, 'Etihad Stadium');
INSERT INTO stadium (capacity,fk_city_id,name) VALUES (40157, 1, 'Goodison Park');
INSERT INTO stadium (capacity,fk_city_id,name) VALUES (10356, 15, 'Kenilworth Road');
INSERT INTO stadium (capacity,fk_city_id,name) VALUES (62500, 2, 'London Stadium');
INSERT INTO stadium (capacity,fk_city_id,name) VALUES (31700, 13, 'Molineux Stadium');
INSERT INTO stadium (capacity,fk_city_id,name) VALUES (74140, 6, 'Old Trafford');
INSERT INTO stadium (capacity,fk_city_id,name) VALUES (26255, 2, 'Selhurst Park');
INSERT INTO stadium (capacity,fk_city_id,name) VALUES (52409, 8, 'St James'' Park');
INSERT INTO stadium (capacity,fk_city_id,name) VALUES (41837, 2, 'Stamford Bridge');
INSERT INTO stadium (capacity,fk_city_id,name) VALUES (62062, 2, 'Tottenham Hotspur Stadium');
INSERT INTO stadium (capacity,fk_city_id,name) VALUES (21944, 17, 'Turf Moor');
INSERT INTO stadium (capacity,fk_city_id,name) VALUES (42788, 4, 'Villa Park');
INSERT INTO stadium (capacity,fk_city_id,name) VALUES (11464, 11, 'Vitality Stadium');
INSERT INTO stadium (capacity,fk_city_id,name) VALUES (26688, 14, 'The Hawthorns');
INSERT INTO stadium (capacity,fk_city_id,name) VALUES (32261, 7, 'King Power Stadium');
INSERT INTO stadium (capacity,fk_city_id,name) VALUES (37890, 5, 'Elland Road');
INSERT INTO stadium (capacity,fk_city_id,name) VALUES (32384, 9, 'St Mary''s Stadium');
INSERT INTO stadium (capacity,fk_city_id,name) VALUES (27244, 18, 'Carrow Road');
INSERT INTO stadium (capacity,fk_city_id,name) VALUES (21577, 19, 'Vicarage Road');

INSERT INTO league(name, season) VALUES ('Premier League','23/24');
INSERT INTO league(name, season) VALUES ('Premier League','22/23');
INSERT INTO league(name, season) VALUES ('Premier League','21/22');
INSERT INTO league(name, season) VALUES ('Premier League','20/21');
INSERT INTO league(name, season) VALUES ('Premier League','19/20');

INSERT INTO owner(full_name, country) VALUES ('John Henry', 'USA');
INSERT INTO owner(full_name, country) VALUES ('Tony Bloom', 'England');
INSERT INTO owner(full_name, country) VALUES ('Abdullah bin Musa''ed', 'Saudi Arabia');
INSERT INTO owner(full_name, country) VALUES ('Matthew Benham', 'England');
INSERT INTO owner(full_name, country) VALUES ('Evangelos Marinakis', 'Greece');
INSERT INTO owner(full_name, country) VALUES ('Shahid Khan of Flex-N-Gate', 'USA');
INSERT INTO owner(full_name, country) VALUES ('Stan Kroenke', 'USA');
INSERT INTO owner(full_name, country) VALUES ('Abu Dhabi United Group', 'UAE');
INSERT INTO owner(full_name, country) VALUES ('Farhad Moshiri', 'UK');
INSERT INTO owner(full_name, country) VALUES ('Luton Town Supporters'' Trust', 'England');
INSERT INTO owner(full_name, country) VALUES ('David Sulliva ', 'Wales');
INSERT INTO owner(full_name, country) VALUES ('Fosun Group', 'China');
INSERT INTO owner(full_name, country) VALUES ('the Glazers family', 'USA');
INSERT INTO owner(full_name, country) VALUES ('John Textor', 'USA');
INSERT INTO owner(full_name, country) VALUES ('Public Investment Fund', 'Saudi Arabia');
INSERT INTO owner(full_name, country) VALUES ('Todd Boehly', 'USA');
INSERT INTO owner(full_name, country) VALUES ('Joe Lewis', 'USA');
INSERT INTO owner(full_name, country) VALUES ('Alan Pace', 'USA');
INSERT INTO owner(full_name, country) VALUES ('Nassef Sawiris', 'Egypt');
INSERT INTO owner(full_name, country) VALUES ('William P. Foley', 'USA');
INSERT INTO owner(full_name, country) VALUES ('Lai Guochuan', 'China');
INSERT INTO owner(full_name, country) VALUES ('Aiyawatt Srivaddhanaprabha', 'Thailand');
INSERT INTO owner(full_name, country) VALUES ('49ers Enterprises', 'USA');
INSERT INTO owner(full_name, country) VALUES ('Dragan Šolak', 'Serbia');
INSERT INTO owner(full_name, country) VALUES ('Michael Wynn Jones', 'Wales');
INSERT INTO owner(full_name, country) VALUES ('Gino Pozzo', 'Italy');

INSERT INTO club(name, year_of_establishment,fk_st_id,in_first_league, fk_owner_id) VALUES('Liverpool', 1892, 2, true,1);
INSERT INTO club(name, year_of_establishment,fk_st_id,in_first_league, fk_owner_id) VALUES('Brighton & Hove Albion', 1901, 1, true,2);
INSERT INTO club(name, year_of_establishment,fk_st_id,in_first_league, fk_owner_id) VALUES('Sheffield United', 1889, 3, true,3);
INSERT INTO club(name, year_of_establishment,fk_st_id,in_first_league, fk_owner_id) VALUES('Brentford', 1889, 4, true, 4);
INSERT INTO club(name, year_of_establishment,fk_st_id,in_first_league, fk_owner_id) VALUES('Nottingham Forest', 1865, 5, true, 5);
INSERT INTO club(name, year_of_establishment,fk_st_id,in_first_league, fk_owner_id) VALUES('Fulham', 1879, 6, true, 6);
INSERT INTO club(name, year_of_establishment,fk_st_id,in_first_league, fk_owner_id) VALUES('Arsenal', 1886, 7, true, 7);
INSERT INTO club(name, year_of_establishment,fk_st_id,in_first_league, fk_owner_id) VALUES('Manchester City', 1894, 8, true, 8);
INSERT INTO club(name, year_of_establishment,fk_st_id,in_first_league, fk_owner_id) VALUES('Everton', 1878, 9, true, 9);
INSERT INTO club(name, year_of_establishment,fk_st_id,in_first_league, fk_owner_id) VALUES('Luton Town', 1885, 10, true, 10);
INSERT INTO club(name, year_of_establishment,fk_st_id,in_first_league, fk_owner_id) VALUES('West Ham United', 1895, 11, true, 11);
INSERT INTO club(name, year_of_establishment,fk_st_id,in_first_league, fk_owner_id) VALUES('Wolverhampton Wanderers', 1877, 12, true, 12);
INSERT INTO club(name, year_of_establishment,fk_st_id,in_first_league, fk_owner_id) VALUES('Manchester United', 1878, 13, true, 13);
INSERT INTO club(name, year_of_establishment,fk_st_id,in_first_league, fk_owner_id) VALUES('Crystal Palace', 1861, 14, true, 14);
INSERT INTO club(name, year_of_establishment,fk_st_id,in_first_league, fk_owner_id) VALUES('Newcastle United', 1895, 15, true, 15);
INSERT INTO club(name, year_of_establishment,fk_st_id,in_first_league, fk_owner_id) VALUES('Chelsea', 1905, 16, true, 16);
INSERT INTO club(name, year_of_establishment,fk_st_id,in_first_league, fk_owner_id) VALUES('Tottenham Hotspur', 1882, 17, true, 17);
INSERT INTO club(name, year_of_establishment,fk_st_id,in_first_league, fk_owner_id) VALUES('Burnley', 1882, 18, true, 18);
INSERT INTO club(name, year_of_establishment,fk_st_id,in_first_league, fk_owner_id) VALUES('Aston Villa', 1874, 19, true, 19);
INSERT INTO club(name, year_of_establishment,fk_st_id,in_first_league, fk_owner_id) VALUES('Bournemouth', 1899, 20, true, 20);
INSERT INTO club(name, year_of_establishment,fk_st_id,in_first_league, fk_owner_id) VALUES('West Bromwich Albion', 1878, 21, false, 21);
INSERT INTO club(name, year_of_establishment,fk_st_id,in_first_league, fk_owner_id) VALUES('Leicester City', 1884, 22, false, 22);
INSERT INTO club(name, year_of_establishment,fk_st_id,in_first_league, fk_owner_id) VALUES('Leeds United', 1919, 23, false, 23);
INSERT INTO club(name, year_of_establishment,fk_st_id,in_first_league, fk_owner_id) VALUES('Southampton', 1885, 24, false, 24);
INSERT INTO club(name, year_of_establishment,fk_st_id,in_first_league, fk_owner_id) VALUES('Norwich', 1902, 25, false, 25);
INSERT INTO club(name, year_of_establishment,fk_st_id,in_first_league, fk_owner_id) VALUES('Watford', 1881, 26, false, 26);

INSERT INTO main_referee(name, surname) VALUES('Anthony','Taylor');
INSERT INTO main_referee(name, surname) VALUES('Michael','Oliver');
INSERT INTO main_referee(name, surname) VALUES('Paul','Tierney');
INSERT INTO main_referee(name, surname) VALUES('Andy','Madley');
INSERT INTO main_referee(name, surname) VALUES('Tim','Robinson');
INSERT INTO main_referee(name, surname) VALUES('John','Brooks');
INSERT INTO main_referee(name, surname) VALUES('Simon','Hooper');
INSERT INTO main_referee(name, surname) VALUES('Robert','Jones');
INSERT INTO main_referee(name, surname) VALUES('Chris','Kavanagh');
INSERT INTO main_referee(name, surname) VALUES('Jarred','Gillett');
INSERT INTO main_referee(name, surname) VALUES('Stuart','Attwell');
INSERT INTO main_referee(name, surname) VALUES('Samuel','Barrott');
INSERT INTO main_referee(name, surname) VALUES('Craig','Pawson');
INSERT INTO main_referee(name, surname) VALUES('David','Coote');
INSERT INTO main_referee(name, surname) VALUES('Peter','Bankes');
INSERT INTO main_referee(name, surname) VALUES('Michael','Salisbury');
INSERT INTO main_referee(name, surname) VALUES('Thomas','Bramall');
INSERT INTO main_referee(name, surname) VALUES('Darren','England');
INSERT INTO main_referee(name, surname) VALUES('Tony','Harrington');
INSERT INTO main_referee(name, surname) VALUES('Josh','Smith');
INSERT INTO main_referee(name, surname) VALUES('Darren','Bond');
INSERT INTO main_referee(name, surname) VALUES('Graham','Scott');
INSERT INTO main_referee(name, surname) VALUES('Lewis','Smith');
INSERT INTO main_referee(name, surname) VALUES('Rebecca','Welch');
INSERT INTO main_referee(name, surname) VALUES('Sam','Allison');
INSERT INTO main_referee(name, surname) VALUES('Robert','Madley');

INSERT INTO main_referee_leagues(main_referee_id, leagues_league_id) VALUES (1,1);
INSERT INTO main_referee_leagues(main_referee_id, leagues_league_id) VALUES (2,1);
INSERT INTO main_referee_leagues(main_referee_id, leagues_league_id) VALUES (3,1);
INSERT INTO main_referee_leagues(main_referee_id, leagues_league_id) VALUES (4,1);
INSERT INTO main_referee_leagues(main_referee_id, leagues_league_id) VALUES (5,1);
INSERT INTO main_referee_leagues(main_referee_id, leagues_league_id) VALUES (6,1);
INSERT INTO main_referee_leagues(main_referee_id, leagues_league_id) VALUES (7,1);
INSERT INTO main_referee_leagues(main_referee_id, leagues_league_id) VALUES (8,1);
INSERT INTO main_referee_leagues(main_referee_id, leagues_league_id) VALUES (9,1);
INSERT INTO main_referee_leagues(main_referee_id, leagues_league_id) VALUES (10,1);
INSERT INTO main_referee_leagues(main_referee_id, leagues_league_id) VALUES (11,1);
INSERT INTO main_referee_leagues(main_referee_id, leagues_league_id) VALUES (12,1);
INSERT INTO main_referee_leagues(main_referee_id, leagues_league_id) VALUES (13,1);
INSERT INTO main_referee_leagues(main_referee_id, leagues_league_id) VALUES (14,1);
INSERT INTO main_referee_leagues(main_referee_id, leagues_league_id) VALUES (15,1);
INSERT INTO main_referee_leagues(main_referee_id, leagues_league_id) VALUES (16,1);
INSERT INTO main_referee_leagues(main_referee_id, leagues_league_id) VALUES (17,1);
INSERT INTO main_referee_leagues(main_referee_id, leagues_league_id) VALUES (18,1);
INSERT INTO main_referee_leagues(main_referee_id, leagues_league_id) VALUES (19,1);
INSERT INTO main_referee_leagues(main_referee_id, leagues_league_id) VALUES (20,1);
INSERT INTO main_referee_leagues(main_referee_id, leagues_league_id) VALUES (21,1);
INSERT INTO main_referee_leagues(main_referee_id, leagues_league_id) VALUES (22,1);
INSERT INTO main_referee_leagues(main_referee_id, leagues_league_id) VALUES (23,1);
INSERT INTO main_referee_leagues(main_referee_id, leagues_league_id) VALUES (24,1);
INSERT INTO main_referee_leagues(main_referee_id, leagues_league_id) VALUES (25,1);
INSERT INTO main_referee_leagues(main_referee_id, leagues_league_id) VALUES (26,1);

INSERT INTO round(fk_league_id, round_number) VALUES (1,1);
INSERT INTO round(fk_league_id, round_number) VALUES (1,2);
INSERT INTO round(fk_league_id, round_number) VALUES (1,3);
INSERT INTO round(fk_league_id, round_number) VALUES (1,4);
INSERT INTO round(fk_league_id, round_number) VALUES (1,5);
INSERT INTO round(fk_league_id, round_number) VALUES (1,6);
INSERT INTO round(fk_league_id, round_number) VALUES (1,7);
INSERT INTO round(fk_league_id, round_number) VALUES (1,8);
INSERT INTO round(fk_league_id, round_number) VALUES (1,9);
INSERT INTO round(fk_league_id, round_number) VALUES (1,10);
INSERT INTO round(fk_league_id, round_number) VALUES (1,11);
INSERT INTO round(fk_league_id, round_number) VALUES (1,12);
INSERT INTO round(fk_league_id, round_number) VALUES (1,13);
INSERT INTO round(fk_league_id, round_number) VALUES (1,14);
INSERT INTO round(fk_league_id, round_number) VALUES (1,15);
INSERT INTO round(fk_league_id, round_number) VALUES (1,16);
INSERT INTO round(fk_league_id, round_number) VALUES (1,17);
INSERT INTO round(fk_league_id, round_number) VALUES (1,18);
INSERT INTO round(fk_league_id, round_number) VALUES (1,19);
INSERT INTO round(fk_league_id, round_number) VALUES (1,20);
INSERT INTO round(fk_league_id, round_number) VALUES (1,21);
INSERT INTO round(fk_league_id, round_number) VALUES (1,22);
INSERT INTO round(fk_league_id, round_number) VALUES (1,23);
INSERT INTO round(fk_league_id, round_number) VALUES (1,24);
INSERT INTO round(fk_league_id, round_number) VALUES (1,25);
INSERT INTO round(fk_league_id, round_number) VALUES (1,26);
INSERT INTO round(fk_league_id, round_number) VALUES (1,27);
INSERT INTO round(fk_league_id, round_number) VALUES (1,28);
INSERT INTO round(fk_league_id, round_number) VALUES (1,29);
INSERT INTO round(fk_league_id, round_number) VALUES (1,30);
INSERT INTO round(fk_league_id, round_number) VALUES (1,31);
INSERT INTO round(fk_league_id, round_number) VALUES (1,32);
INSERT INTO round(fk_league_id, round_number) VALUES (1,33);
INSERT INTO round(fk_league_id, round_number) VALUES (1,34);
INSERT INTO round(fk_league_id, round_number) VALUES (1,35);
INSERT INTO round(fk_league_id, round_number) VALUES (1,36);
INSERT INTO round(fk_league_id, round_number) VALUES (1,37);
INSERT INTO round(fk_league_id, round_number) VALUES (1,38);

INSERT INTO manager(name, surname, manager_type, fk_club_id) VALUES ('Mikel', 'Arteta', 0, 7);
INSERT INTO manager(name, surname, manager_type, fk_club_id, head_manager_id) VALUES ('Albert', 'Stuivenberg', 1, 7, 1);
INSERT INTO manager(name, surname, manager_type, fk_club_id) VALUES ('Unai', 'Emery', 0, 19);
INSERT INTO manager(name, surname, manager_type, fk_club_id, head_manager_id) VALUES ('Pako', 'Ayestarán', 1, 19, 3);
INSERT INTO manager(name, surname, manager_type, fk_club_id) VALUES ('Andoni', 'Iraola', 0, 20);
INSERT INTO manager(name, surname, manager_type, fk_club_id, head_manager_id) VALUES ('Tommy', 'Elphick', 1, 20, 5);
INSERT INTO manager(name, surname, manager_type, fk_club_id) VALUES ('Thomas', 'Frank', 0, 4);
INSERT INTO manager(name, surname, manager_type, fk_club_id, head_manager_id) VALUES ('Claus', 'Nørgaard', 1, 4, 7);
INSERT INTO manager(name, surname, manager_type, fk_club_id) VALUES ('Roberto', 'De Zerbi', 0, 2);
INSERT INTO manager(name, surname, manager_type, fk_club_id, head_manager_id) VALUES ('Andrea', 'Maldera', 1, 2, 9);
INSERT INTO manager(name, surname, manager_type, fk_club_id) VALUES ('Vincent', 'Kompany', 0, 18);
INSERT INTO manager(name, surname, manager_type, fk_club_id, head_manager_id) VALUES ('Craig', 'Bellamy', 1, 18, 11);
INSERT INTO manager(name, surname, manager_type, fk_club_id) VALUES ('Mauricio', 'Pochettino', 0, 16);
INSERT INTO manager(name, surname, manager_type, fk_club_id, head_manager_id) VALUES ('Jesús', 'Pérez', 1, 16, 13);
INSERT INTO manager(name, surname, manager_type, fk_club_id) VALUES ('Oliver', 'Glasner', 0, 14);
INSERT INTO manager(name, surname, manager_type, fk_club_id, head_manager_id) VALUES ('Paddy', 'McCarthy', 1, 14, 15);
INSERT INTO manager(name, surname, manager_type, fk_club_id) VALUES ('Sean', 'Dyche', 0, 9);
INSERT INTO manager(name, surname, manager_type, fk_club_id, head_manager_id) VALUES ('Ian', 'Woan', 1, 9, 17);
INSERT INTO manager(name, surname, manager_type, fk_club_id) VALUES ('Marco', 'Silva', 0, 6);
INSERT INTO manager(name, surname, manager_type, fk_club_id, head_manager_id) VALUES ('Stuart', 'Gray', 1, 6, 19);
INSERT INTO manager(name, surname, manager_type, fk_club_id) VALUES ('Jürgen', 'Klopp', 0, 1);
INSERT INTO manager(name, surname, manager_type, fk_club_id, head_manager_id) VALUES ('Pepijin', 'Lijnders', 1, 1, 21);
INSERT INTO manager(name, surname, manager_type, fk_club_id) VALUES ('Rob', 'Edwards', 0, 10);
INSERT INTO manager(name, surname, manager_type, fk_club_id, head_manager_id) VALUES ('Richie', 'Kyle', 1, 10, 23);
INSERT INTO manager(name, surname, manager_type, fk_club_id) VALUES ('Pep', 'Guardiola', 0, 8);
INSERT INTO manager(name, surname, manager_type, fk_club_id, head_manager_id) VALUES ('Rodolfo', 'Borrell', 1, 8, 25);
INSERT INTO manager(name, surname, manager_type, fk_club_id) VALUES ('Erik', 'ten Hag', 0, 13);
INSERT INTO manager(name, surname, manager_type, fk_club_id, head_manager_id) VALUES ('Mitchell', 'van der Gaag', 1, 13, 27);
INSERT INTO manager(name, surname, manager_type, fk_club_id) VALUES ('Eddie', 'Howe', 0, 15);
INSERT INTO manager(name, surname, manager_type, fk_club_id, head_manager_id) VALUES ('Jason', 'Tindal', 1, 15, 29);
INSERT INTO manager(name, surname, manager_type, fk_club_id) VALUES ('Nuno', 'Espirito Santo', 0, 5);
INSERT INTO manager(name, surname, manager_type, fk_club_id, head_manager_id) VALUES ('Rui Pedro', 'Silva', 1, 5, 31);
INSERT INTO manager(name, surname, manager_type, fk_club_id) VALUES ('Chris', 'Wilder', 0, 3);
INSERT INTO manager(name, surname, manager_type, fk_club_id, head_manager_id) VALUES ('Alan', 'Knill', 1, 3, 33);
INSERT INTO manager(name, surname, manager_type, fk_club_id) VALUES ('Ange', 'Postecoglou', 0, 17);
INSERT INTO manager(name, surname, manager_type, fk_club_id, head_manager_id) VALUES ('Mile', 'Jedinak', 1, 17, 35);
INSERT INTO manager(name, surname, manager_type, fk_club_id) VALUES ('David', 'Moyes', 0, 11);
INSERT INTO manager(name, surname, manager_type, fk_club_id, head_manager_id) VALUES ('Billy', 'McKinlay', 1, 11, 37);
INSERT INTO manager(name, surname, manager_type, fk_club_id) VALUES ('Gary', 'O''Neil', 0, 12);
INSERT INTO manager(name, surname, manager_type, fk_club_id, head_manager_id) VALUES ('Tim', 'Jenkins', 1, 12, 39);

